// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo7gci6goSEVejbs2DVYHPZ5-XqObJaAM',
    appId: '1:77389885248:web:8e0439b702fb9c13b854a5',
    messagingSenderId: '77389885248',
    projectId: 'sanyukt-7d18d',
    authDomain: 'sanyukt-7d18d.firebaseapp.com',
    storageBucket: 'sanyukt-7d18d.firebasestorage.app',
    measurementId: 'G-JH787FR858',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDImRM4DvyPp0l716oVji6c6UcUsokFqZg',
    appId: '1:77389885248:android:2e408334ac08cc31b854a5',
    messagingSenderId: '77389885248',
    projectId: 'sanyukt-7d18d',
    storageBucket: 'sanyukt-7d18d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAY5j-jk6CltJ17yuAjRF9528-HYQv1Tk',
    appId: '1:77389885248:ios:4cc76fc9781e6624b854a5',
    messagingSenderId: '77389885248',
    projectId: 'sanyukt-7d18d',
    storageBucket: 'sanyukt-7d18d.firebasestorage.app',
    iosBundleId: 'com.example.sanyukt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAY5j-jk6CltJ17yuAjRF9528-HYQv1Tk',
    appId: '1:77389885248:ios:4cc76fc9781e6624b854a5',
    messagingSenderId: '77389885248',
    projectId: 'sanyukt-7d18d',
    storageBucket: 'sanyukt-7d18d.firebasestorage.app',
    iosBundleId: 'com.example.sanyukt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo7gci6goSEVejbs2DVYHPZ5-XqObJaAM',
    appId: '1:77389885248:web:7a1dc0929fa6c4ccb854a5',
    messagingSenderId: '77389885248',
    projectId: 'sanyukt-7d18d',
    authDomain: 'sanyukt-7d18d.firebaseapp.com',
    storageBucket: 'sanyukt-7d18d.firebasestorage.app',
    measurementId: 'G-TZ3ENMZENN',
  );

  /// OAuth 2.0 Web client ID for Google Sign-In (required on Android as serverClientId).
  /// Get from: Firebase Console → Project settings → Your apps → Web app (client ID),
  /// or Google Cloud Console → APIs & Services → Credentials → OAuth 2.0 Client IDs (Web application).
  static const String googleSignInWebClientId =
      '77389885248-549qdsdkdl78ulpfquvsf2v80hukrkah.apps.googleusercontent.com';
      
}
