/**
 * Profile form dropdown options. Served by GET /user/profile/options.
 * Single API for all dropdown lists used in profile update.
 */
export const profileOptions = {
  bloodGroup: [
    'A+',
    'A-',
    'B+',
    'B-',
    'AB+',
    'AB-',
    'O+',
    'O-',
    'Unknown',
  ],
  jainSect: [
    'Digambara',
    'Shwetambar',
    'Sthanakvasi',
    'Terapanthi',
    'Murtipujak (Deravasi)',
    'Other',
  ],
  motherTongue: [
    'Gujarati',
    'Kutchi',
    'Hindi',
    'Marwari',
    'Rajasthani',
    'Marathi',
    'Malvi',
    'Bundeli',
    'Kannada',
    'Tamil',
    'Telugu',
    'Urdu',
    'Bengali',
    'Punjabi',
    'Sindhi',
    'Other',
  ],
  highestQualification: [
    '10th or below 10th',
    'Professional courses',
    '12th Pass',
    'Diploma',
    'ITI',
    'Undergraduate (UG)',
    'Postgraduate (PG)',
    'PhD / Doctorate',
    'Other',
  ],
  fieldOfStudy: [
    'Science',
    'Commerce',
    'Arts / Humanities',
    'Engineering',
    'Medical / Healthcare',
    'Information Technology (IT)',
    'Computer Science',
    'Business Administration (BBA/MBA)',
    'Law',
    'Education / Teaching',
    'Design / Creative Arts',
    'Architecture',
    'Finance / Accounting',
    'Marketing',
    'Psychology',
    'Media / Communication',
    'Hospitality / Tourism',
    'Agriculture',
    'Other',
  ],
  employmentType: [
    'Private Sector Job',
    'Business (Self Employed)',
    'Government Sector Job',
    'Student',
    'Other',
  ],
  industrySector: [
    'Diamond / Gems',
    'Textiles',
    'Information Technology (IT)',
    'Finance / Banking',
    'Healthcare',
    'Manufacturing',
    'Retail / Trading',
    'Real Estate',
    'Education',
    'Agriculture',
    'Food & Beverage',
    'Construction',
    'Media / Entertainment',
    'Consulting',
    'Other',
  ],
  maritalStatus: [
    'Single',
    'Married',
    'Engaged',
    'Divorced',
    'Widowed',
    'Separated',
  ],
  gender: ['Male', 'Female', 'Other'],
  isEmployer: ['Yes', 'No'],
} as const;

export type ProfileOptionsKey = keyof typeof profileOptions;
